"""Backend protocol for MAVLink bridges."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from sentinel.common.types import GeoPoint, MissionPlan

from .commands import CommandResult
from .telemetry import TelemetrySnapshot


@runtime_checkable
class MavlinkBackend(Protocol):
    def connect(self) -> CommandResult: ...
    def arm(self) -> CommandResult: ...
    def disarm(self) -> CommandResult: ...
    def takeoff(self, altitude_m: float) -> CommandResult: ...
    def land(self) -> CommandResult: ...
    def return_home(self) -> CommandResult: ...
    def hold(self) -> CommandResult: ...
    def goto(self, point: GeoPoint) -> CommandResult: ...
    def upload_mission(self, plan: MissionPlan) -> CommandResult: ...
    def start_mission(self) -> CommandResult: ...
    def get_telemetry(self) -> TelemetrySnapshot: ...
    def close(self) -> None: ...
